name: Build QMK Firmware
on:
  schedule:
  - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keymap:
        - via
        - default

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        ref: develop
        submodules: true

    - name: Build ${{ matrix.keymap }} keymaps
      continue-on-error: true
      run: qmk -v mass-compile -j3 -km ${{ matrix.keymap }}

    - name: Sort output
      shell: bash
      run: |
        for file in *.hex *.bin *.uf2; do
          DIR=fw_output/$(echo $file | cut -d'_' -f1)
          [ -f "$file" ] && (mkdir -p "$DIR"; mv -v "$file" "$DIR/") || true
        done

    - name: Archive ${{ matrix.keymap }} firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: fw_output
        path: fw_output/
        retention-days: 1 

  upload:
    needs: build
    uses: filterpaper/scripts/.github/workflows/commit-artifact.yml@main
    with:
      artifact_name: fw_output
      artifact_folder: .

  purge:
    needs: build
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main

